name: Release

on:
  push:
    tags:
      - 'v*'

env:
  DOCKER_REPOSITORY_NAME: ruby-community
  DEPOT_REPOSITORY_NAME: 'agents/ruby-community'
  ECR_REGISTRY: public.ecr.aws/odigos/agents
  DEPOT_REGISTRY: p0xd21zf5r.registry.depot.dev

jobs:
  release:
    runs-on: depot-ubuntu-24.04-4
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-ecr-upload
          aws-region: 'us-east-1'

      - name: Log in to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws

      - name: Login to Depot Registry
        run: echo "${{ secrets.DEPOT_DEV_AGENT_PUBLISH_TOKEN }}" | docker login ${DEPOT_REGISTRY} -u x-token --password-stdin

      - name: Compute Docker tags
        id: docker-tags
        env:
          TAG: ${{ github.ref_name }}
        run: |
          echo "tags=${ECR_REGISTRY}/${DOCKER_REPOSITORY_NAME}:${TAG},${DEPOT_REGISTRY}/${DEPOT_REPOSITORY_NAME}:${TAG},${ECR_REGISTRY}/${DOCKER_REPOSITORY_NAME}:latest,${DEPOT_REGISTRY}/${DEPOT_REPOSITORY_NAME}:latest" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: release.Dockerfile
          push: true
          build-args: AGENT_VERSION=${{ github.ref_name }}
          tags: ${{ steps.docker-tags.outputs.tags }}

      - name: Notify Slack
        uses: odigos-io/ci-core/.github/actions/slack-release-notification@main
        with:
          webhook-url: ${{ secrets.ODIGOS_RELEASE_STATUS_WEBHOOK_URL }}
          success-description: "Published a new release of OpenTelemetry Ruby Community Agent"
          failure-description: "ERROR: Failed to publish a new release of OpenTelemetry Ruby Community Agent"
          tag: ${{ github.ref_name }}

  # Trigger Odigos version update (OSS, Enterprise, VM Agent)
  trigger-odigos-update:
    needs: release
    runs-on: depot-ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Trigger agents version update in consumer repos
        uses: odigos-io/ci-core/dispatch-agent-version-update@main
        with:
          instrumentation_agent: ruby
          version: ${{ github.ref_name }}
          consumers: |
            odigos
            odigos-enterprise
            vm-agent
